In [28]:
import matplotlib.pyplot as plt
import geopandas as gpd
import pandas as pd
import shapely as shy
from shapely.ops import nearest_points
from shapely.geometry import Point, MultiPoint
import fiona
from fiona.crs import from_epsg
from scipy.spatial import cKDTree
import numpy as np
import osmnx as ox
import pysal as ps
from pylab import figure, scatter, show

pd.options.display.max_rows = 4
%matplotlib inline
import os
os.environ["PROJ_LIB"] = "C:\ProgramData\Anaconda3\Library\share" #window

In [2]:
#Filepaths
work = r"D:"
laptop = r"C:\Users\jerem"
origin = work

In [4]:
fp =  r"\Box Sync\Policy Evaluation\working_data\analytical_panel_shapefile\analytical_panel_qt_shapefile.shp"
df = gpd.read_file(origin+fp)

In [5]:
df.head(2)

,collision_,personsinj,pedestrian,cyclistinj,motoristin,bronx,brooklyn,manhattan,queens,statenisla,...,bike_rou_1,flag_senio,flag_prior,flag_schoo,quarter,year,intersecti,y,x,geometry
0,3,0,0,0,0,0,0,1,0,0,...,1,1,1,0,1,2013,1,199793.6093,986336.149,POINT (986336.149 199793.609300002)
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,2013,2,202206.1619,982769.331,POINT (982769.331 202206.161899999)

In [19]:
## Spatial weights to be calculate on quarter==3 & year == 2012
sub_df = df['quarter'] == 3
df1 = df[sub_df]
sub_df = df1['year'] == 2012
df1 = df1[sub_df]
df1.head()

,collision_,personsinj,pedestrian,cyclistinj,motoristin,bronx,brooklyn,manhattan,queens,statenisla,...,bike_rou_1,flag_senio,flag_prior,flag_schoo,quarter,year,intersecti,y,x,geometry
155844,6,1,1,0,0,0,0,1,0,0,...,1,1,1,0,3,2012,1,199793.6093,986336.1490,POINT (986336.149 199793.609300002)
155845,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,3,2012,2,202206.1619,982769.3310,POINT (982769.331 202206.161899999)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155847,1,0,0,0,0,0,0,1,0,0,...,1,0,0,0,3,2012,4,201529.9618,982812.2555,POINT (982812.255500004 201529.961799994)
155848,5,1,0,0,1,0,0,1,0,0,...,1,0,0,0,3,2012,5,201226.1097,982816.3956,POINT (982816.395600006 201226.109699994)

In [23]:
df1['intersecti'].count()

12987

In [31]:
south, west, north, east = df1.unary_union.buffer(0.1).bounds

In [32]:
print(south, west, north, east)

914216.166399994 122548.7583 1067113.31250001 271727.03490000096

In [25]:
fp =  r"\Box Sync\Policy Evaluation\working_data\analytical_panel_shapefile\analytical_panel_qt_shapefile_crosssec.shp"
df1.to_file(origin+fp)

In [30]:
fp =  r"\Box Sync\Policy Evaluation\working_data\analytical_panel_shapefile\analytical_panel_qt_shapefile_crosssec.shp"
rW = ps.rook_from_shapefile(origin+fp)

AttributeError: 'Point' object has no attribute 'bbox'